module.exports = {
  query: '',
  steps: [
    ['eval', 'Sound.unlock(); Title.show()'],
    ['new', 'TESTER'],
    ['shot', 'd1_intro'],
    ['door', 'house'],
    ['use', -3.8, 6.6], ['use', 1.6, 7.2], ['use', 4.5, 1.4],
    ['check', "Game.st.obj.id === 'milk'"],
    ['use', -6.4, -6.2],
    ['door', 'town'],
    ['door', 'market'],
    ['use', 6.8, -3],
    ['talk', 'priya'],
    ['door', 'town'],
    ['door', 'house'],
    ['use', -6.4, -6.2],
    ['check', "Game.st.obj.id === 'trash'"],
    ['use', -2.6, -1],
    ['door', 'town'],
    ['use', 12.5, 15.9],
    ['check', "Game.st.obj.id === 'visitaq'"],
    ['door', 'aquarium'],
    ['shot', 'd1_aq_lobby'],
    ['talk', 'dana'],
    ['use', -8.8, 12.5],
    ['talk', 'walter'],
    ['shot', 'd1_after_tour'],
    ['check', "Game.st.flags.hired"],
    ['door', '*use'],
    ['door', 'house'],
    ['answers', [0, 1]],
    ['use', 5.8, -5],
    ['shot', 'd2_start'],
    ['print', 'T.summary()'],
  ],
};
