const sleep = [['answers', [0, 1]], ['use', 5.8, -5]];
module.exports = {
  query: 'debug&day=5&map=house&spawn=bed&run=1',
  steps: [
    ['wait', 1500],
    ['door', 'town'], ['use', 20.5, 16.2],
    ['check', "Game.st.inv.includes('bday_card')"],
    ['door', 'aquarium'], ['answers', [0]], ['talk', 'walter'],
    ['check', "Game.st.obj.id === 'inventory'"],
    ['answers', [0]], ['use', -1.6, 14.5],
    ['check', "Game.st.flags.cardThrown"],
    ['answers', [0]], ['use', -1.6, 14.5],
    ['use', 43.5, -32], ['use', 39.4, -38.5],
    ['check', "Game.st.obj.id === 'brochures'"],
    ['door', 'town'], ['door', 'school'], ['talk', 'okafor'], ['use', 12.5, 3.0], ['use', -4.6, -2.6],
    ['check', "Game.st.inv.includes('notebook')"],
    ['door', 'town'], ['talk', 'ray'], ['door', 'laundry'], ['talk', 'mae'], ['door', 'town'],
    ['door', 'aquarium'], ['answers', [0]], ['talk', 'walter'],
    ['check', "Game.st.obj.id === 'kitchen5'"],
    ['use', 19.8, -38.3], ['use', 25.2, -38],
    ['check', "Game.st.obj.id === 'secret'"],
    ['shot', 'd5_kitchen'],
    ['door', 'town'], ['answers', [1]], ['talk', 'miller'],
    ['check', "Game.st.obj.id === 'home5'"],
    ['door', 'house'],
    ['use', -2.6, -6.5],
    ...sleep,
    // ---------------- DAY 6
    ['check', "Game.st.day === 6"],
    ['door', 'town'], ['use', 20.5, 16.2], ['door', 'aquarium'], ['talk', 'walter'],
    ['check', "Game.st.obj.id && Game.st.obj.id === 'bulbs'"],
    ['use', 39.4, -38.5], ['use', -6, -1.4], ['use', 7, -12.4], ['use', -4, -26.4],
    ['check', "Game.st.obj.id === 'lunch6'"],
    ['use', 18, -38.2], ['doorAt', 31.5, -28],
    ['check', "Game.st.obj.id === 'desk6'"],
    ['tp', 31.5, -35.5], ['use', 31.5, -36.2],
    ['shot', 'd6_office'],
    ['use', 31.5, -36.2], ['use', 31.5, -36.2], ['use', 34.6, -37.8], ['use', 34.6, -37.8], ['use', 33.9, -38.9], ['use', 28.5, -38.8],
    ['answers', [0]], ['tp', 31.5, -25], ['wait', 2000],
    ['check', "Game.st.obj.id === 'home6'"],
    ['door', 'town'], ['door', 'house'], ['use', -2.6, -6.5],
    ...sleep,
    ['check', "Game.st.day === 7"],
    ['print', 'T.summary()'],
  ],
};
