module.exports = {
  query: 'debug&day=7&map=house&spawn=bed&run=1&flags=metEvan,okaforEvan',
  steps: [
    ['wait', 2000],
    ['door', 'town'], ['door', 'aquarium'],
    ['talk', 'dana'],
    ['check', "Game.st.obj.id === 'what'"],
    ['talk', 'gus'], ['talk', 'ray'],
    ['door', 'diner'], ['talk', 'hal'], ['door', 'town'],
    ['check', "Game.st.obj.id === 'home7'"],
    ['use', 60, -35.3], ['use', 10.7, -1.2], ['use', 9.5, 2.8], ['door', 'town', 'gas'],
    ['door', 'laundry'], ['talk', 'mae'], ['talk', 'mae'], ['door', 'town'],
    ['door', 'kessler'], ['use', 2.6, -8.4], ['use', 4.8, -7], ['door', 'town'],
    ['door', 'church'], ['answers', [1]], ['use', -4.8, -9.3], ['door', 'town'],
    ['door', 'house'], ['use', 5.8, -5],
    ['check', "Game.st.tod === 'night'"],
    ['use', -2.6, -6.5],
    ['check', "Game.st.obj.id === 'aq7'"],
    ['door', 'town'], ['door', 'aquarium'],
    ['answers', [0]], ['tp', 0, -22.5], ['wait', 3000], ['wait', 12000],
    ['shot', 'd7_ghost'],
    ['check', "Game.st.obj.id === 'backpack'"],
    ['talk', 'ghost'],
    ['answers', ['0812']], ['use', 49.5, -38.6],
    ['check', "Game.st.inv.includes('backpack')"],
    ['item', 'backpack', 'OPEN'], ['item', 'tape12', 'PLAY'],
    ['doorAt', 53, -25],
    ['use', 5.8, -3], ['use', 2.5, -2], ['use', 0.9, 5.4],
    ['door', 'aquarium'],
    ['use', 52, -33],
    ['door', 'town'],
    ['door', 'house'], ['door', 'evanroom'],
    ['shot', 'd7_evanroom'],
    ['use', -1.8, -0.2],
    ['check', "Game.st.obj.id === 'sleep7'"],
    ['answers', [0, 1]], ['use', -1.8, -0.2],
    ['check', "Game.st.day === 8"],
    ['print', 'T.summary()'],
  ],
};
