const tb = (x, z, item) => [['answers', [0, item]], ['use', x, z + 1.4]];
module.exports = {
  query: 'debug&day=8&map=house&spawn=bed&run=1&flags=metEvan,playedTape&items=tape12,inhaler,feeding_log,phone_bill,concrete,report,toby_letter',
  steps: [
    ['wait', 2500],
    ['eval', 'T.noStealth = true'],
    ['door', 'town'], ['use', 20.5, 16.2], ['door', 'house'],
    ['door', 'evanroom'],
    ['answers', [1, 0]], ['use', 1.9, 1.5],
    ['check', "Game.st.obj.id === 'hang'"],
    ['door', 'house'],
    ['use', 5.2, 0.7],
    ['check', "Game.st.obj.id === 'playground'"],
    ['door', 'town'], ['tp', -25, 44], ['wait', 1500],
    ['shot', 'd8_playground'],
    ['use', -31, 50],
    ['check', "Game.st.inv.includes('key_t6')"],
    ['door', 'house'], ['door', 'basement'],
    ['wait', 1500],
    ['check', "Game.st.obj.id === 'where'"],
    ['use', 5.8, -3], ['use', 2.5, -2], ['use', 0.9, 5.4],
    ['check', "Game.st.flags.remembered"],
    ['door', 'aquarium'],
    ['wait', 800],
    ['shot', 'd8_aquarium'],
    ['talk', 'ghost'],
    ['check', "Game.st.obj.id === 'leaveit'"],
    ['doorAt', 53, -25],
    ['answers', [0]], ['doorAt', 0, -8],
    ['check', "Game.st.flags.tunnelOpen"],
    ['tp', 0, -30], ['wait', 600], ['shot', 'd8_tunnel'],
    ['tp', 2.8, -43.4], ['use', 2.8, -44.2],
    ['check', "Game.st.flags.lightsOut"],
    ['shot', 'd8_dark'],
    ['door', 'aquarium'],
    ['tp', 0, 12], ['wait', 500], ['shot', 'd8_stealth'],
    ['door', 'town'],
    ['check', "Game.st.obj.id === 'gohome8'"],
    ['shot', 'd8_town_night'],
    ['door', 'house'],
    ['door', 'town'],
    ['check', "Game.st.flags.walterInside"],
    ['tp', -3, -3], ['wait', 1500],
    ['check', "Game.st.flags.finalChase"],
    ['shot', 'd8_house_final'],
    ['door', 'evanroom'],
    ['wait', 3000],
    ['check', "Game.st.map === 'underneath'"],
    ['shot', 'd8_underneath'],
    ['tp', 0, -22], ['wait', 3000],
    ...tb(-11, -30, 'feeding_log'),
    ...tb(-13, -39, 'work_order'),
    ...tb(-9, -47, 'tape12'),
    ...tb(0, -50, 'tooth'),
    ['shot', 'd8_hub'],
    ...tb(9, -47, 'phone_bill'),
    ...tb(13, -39, 'concrete'),
    ...tb(11, -30, 'report'),
    ['wait', 12000],
    ['check', "Game.st.map === 'whiteroom'"],
    ['shot', 'd8_white'],
    ['talk', 'evan'],
    ['wait', 5000],
    ['print', '({ mode: Game.mode, endings: State.getMeta().endings })'],
  ],
};
