// Days 1-4 from a real new game.
const sleep = [['answers', [0, 1]], ['use', 5.8, -5]];
module.exports = {
  query: '',
  steps: [
    ['eval', 'Sound.unlock(); Title.show()'],
    ['new', 'TESTER'],
    ['door', 'house'],
    ['use', -3.8, 6.6], ['use', 1.6, 7.2], ['use', 4.5, 1.4],
    ['door', 'town'], ['door', 'market'], ['use', 6.8, -3], ['talk', 'priya'],
    ['door', 'town'], ['door', 'house'], ['use', -6.4, -6.2], ['use', -2.6, -1],
    ['door', 'town'], ['use', 12.5, 15.9],
    ['check', "Game.st.obj.id === 'visitaq'"],
    ['talk', 'miller'],
    ['door', 'aquarium'], ['talk', 'dana'], ['use', -8.8, 12.5], ['talk', 'walter'],
    ['check', "Game.st.flags.hired"],
    ['door', 'town'], ['door', 'house'],
    ...sleep,
    // ---------------- DAY 2
    ['check', "Game.st.day === 2"],
    ['door', 'town'], ['talk', 'miller'], ['door', 'aquarium'],
    ['talk', 'walter'], ['talk', 'dana'],
    ['use', 18, -38.2], ['use', -21.2, -8],
    ['use', -13.4, -1.2], ['use', -13.4, -14.5], ['use', -13.6, -23], ['use', 12.9, -17.5],
    ['use', 39.4, -38.5], ['use', -13.6, -23],
    ['talk', 'walter'],
    ['check', "Game.st.obj.id === 'umbrella'"],
    ['use', 46.6, -35.5], ['use', 41.5, -36.2], ['use', -9.2, 5], ['use', 4.4, 11.6], ['use', 7.8, 13.4], ['use', -19, -17.4], ['use', -7.3, 9.8],
    ['door', 'town'], ['door', 'miller'], ['talk', 'miller'],
    ['door', 'town'], ['use', 31, -81], ['use', 58.5, -88.5], ['talk', 'ray'], ['use', 46.8, -96.2],
    ['door', 'house'], ['use', -6.5, 7.2],
    ...sleep,
    // ---------------- DAY 3
    ['check', "Game.st.day === 3"],
    ['door', 'town'], ['use', 20.5, 16.2], ['door', 'aquarium'],
    ['talk', 'walter'], ['use', 13.4, -4], ['use', 13.4, -9.5], ['use', 18, -38.2], ['use', 13.4, -4],
    ['talk', 'walter'], ['check', "Game.st.obj.id === 'lunch'"],
    ['use', 12.9, -17.5], ['use', 52.2, -30.2],
    ['door', 'town'], ['door', 'diner'], ['talk', 'hal'], ['use', 6.9, -3.6], ['use', -5.5, -5.2],
    ['door', 'town'], ['door', 'aquarium'], ['doorAt', 31.5, -28],
    ['check', "Game.st.obj.id === 'explore'"],
    ['door', 'town'], ['door', 'school'], ['talk', 'okafor'], ['use', -9, -7.8], ['door', 'town'],
    ['talk', 'bea'], ['talk', 'tommy'], ['use', -45, 49.2],
    ['door', 'laundry'], ['talk', 'mae'], ['use', 5.8, 3.6], ['door', 'town'],
    ['check', "Game.st.obj.id === 'home3'"],
    ['item', 'radio3', 'PLAY'],
    ['door', 'house'],
    ...sleep,
    // ---------------- DAY 4
    ['check', "Game.st.day === 4"],
    ['door', 'town'], ['talk', 'miller'], ['door', 'aquarium'],
    ['answers', [0]], ['talk', 'walter'],
    ['check', "Game.st.obj.id === 'sort'"],
    ['answers', [0, 2, 1, 0]], ['use', 7.8, 7.1],
    ['check', "Game.st.obj.id === 'lunch4'"],
    ['tp', 21.5, -31], ['wait', 2500],
    ['check', "Game.st.obj.id === 'eat'"],
    ['shot', 'd4_kitchen'],
    ['answers', [0]], ['item', 'sandwich', 'EAT'],
    ['check', "Game.st.obj.id === 'paycheck'"],
    ['doorAt', 31.5, -28],
    ['check', "Game.st.obj.id === 'home4'"],
    ['door', 'town'], ['door', 'house'], ['use', 0, -8.4],
    ...sleep,
    ['check', "Game.st.day === 5"],
    ['print', 'T.summary()'],
  ],
};
